apiVersion: apps/v1
kind: Deployment

metadata:
  name: myapp-deployment-djangoui
  labels: 
    app: myapp
    type: front-end
    app.kubernetes.io/name: djangoui

spec:
  selector:
    matchLabels:
      app: myapp
      type: front-end
      app.kubernetes.io/name: djangoui
  template:
    metadata:
      name: myapp-pod-djangoui
      labels:
        app: myapp
        type: front-end
        app.kubernetes.io/name: djangoui
    spec:
      imagePullSecrets:
      - name: regcred  
      containers:               
      - name: nginx
        image: meghraj1996/nginx:latest
        ports:
          - containerPort: 5000
            name: nginx-port 
      - name: react-soft-ui
        image: meghraj1996/sample-docker-django-react_react-ui:latest
        ports:
          - containerPort: 3000
            name: react-ui-port          
        env:
        - name: CHOKIDAR_USEPOLLING
          value: "True" 
      - name: appseed-app
        image: meghraj1996/sample-docker-django-react_appseed-app:latest
        env:
        - name: SECRET_KEY
          value: "STRONG_KEY_HERE"
        - name: DEBUG
          value: "True"
        - name: DJANGO_ALLOWED_HOSTS
          value: "localhost 127.0.0.1 [::1]"
        - name: DB_ENGINE
          value: "django.db.backends.sqlite3"
        - name: DATABASE
          value: "db.sqlite3" 