kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx-ex-git
  namespace: prj-django-disseration
  labels:
    app: nginx-ex-git
    app.kubernetes.io/component: nginx-ex-git
    app.kubernetes.io/instance: nginx-ex-git
    app.kubernetes.io/name: nginx-ex-git
    app.kubernetes.io/part-of: nginx-ex-git-app
    app.openshift.io/runtime: nginx
    app.openshift.io/runtime-version: 1.20-ubi7
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-ex-git
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-ex-git
        app.kubernetes.io/name: djangoui
        deployment: nginx-ex-git
        type: front-end
    spec:
      containers:
        - name: nginx-ex-git
          image: >-
            image-registry.openshift-image-registry.svc:5000/prj-django-disseration/nginx-ex-git@sha256:c96a876b7d0efd59328f67dc60cdc794358ff07c7b884ce09d3af32a7f311b12
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8443
              protocol: TCP
        - name: react-soft-ui
          env:
            - name: CHOKIDAR_USEPOLLING
              value: 'True'
          ports:
            - name: react-ui-port
              containerPort: 3000
              protocol: TCP
          image: 'quay.io/meghraj1996/react-ui:latest'
        - name: appseed-app
          image: 'quay.io/meghraj1996/appseed-app:latest'
          env:
            - name: SECRET_KEY
              value: STRONG_KEY_HERE
            - name: DEBUG
              value: 'True'
            - name: DJANGO_ALLOWED_HOSTS
              value: 'localhost 127.0.0.1 [::1]'
            - name: DB_ENGINE
              value: django.db.backends.sqlite3
            - name: DATABASE
              value: db.sqlite3