kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: nginx-ex-git
  namespace: prj-django-disseration
  labels:
    app: nginx-ex-git
    app.kubernetes.io/component: nginx-ex-git
    app.kubernetes.io/instance: nginx-ex-git
    app.kubernetes.io/name: nginx-ex-git
    app.kubernetes.io/part-of: nginx-ex-git-app
    app.openshift.io/runtime: nginx
    app.openshift.io/runtime-version: 1.20-ubi7
  
spec:
  host: >-
    nginx-ex-git-prj-django-disseration.apps.dissertationuel.ot6r.p1.openshiftapps.com
  to:
    kind: Service
    name: nginx-ex-git
    weight: 100
  port:
    targetPort: 8080-tcp
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
status:
  ingress:
    - host: >-
        nginx-ex-git-prj-django-disseration.apps.dissertationuel.ot6r.p1.openshiftapps.com
      routerName: default
      conditions:
        - type: Admitted
          status: 'True'
          lastTransitionTime: '2023-04-16T15:33:06Z'
      wildcardPolicy: None
      routerCanonicalHostname: router-default.apps.dissertationuel.ot6r.p1.openshiftapps.com